public void testBreakInFinally () throws Exception {
    String src = "b: try { throw(\"throw me\") } finally { /* fake catcher */ ; break b }; console.log(\"ok then...\");";
    Script script = ((Context) cx).compileString(src, "", 1, null);
    script.exec(cx, scope);
}
