public void testIssue110() {
    try {
        new Issue110().testIssue110();
    } catch (RuntimeException e) {
        assertEquals("reset() was called", e.getMessage());
    }
}
class Issue110 {
    long uid;
    void reset() {
        uid = Math.round(Math.random());
    }
    void doStuff() {
        reset();
        long _uid = uid;

        if (uid < 0.5) {
            doStuff();
        }

        if (_uid != uid) {
            throw new RuntimeException("reset() was called");
        }
    }
    void testIssue110() {
        doStuff();
    }
}
