public void testFunctionStatement() {
    try {
        Object result = eval("function () {};");
        fail("Should have thrown an Exception");
    }
    catch(Exception e) {
        // Expected
    }
}
