public void testSuper() throws Exception {
    test("testSuper", "1");
}

public void testSuper() {
    var x = {
        a: 10,
        b: function() {
            return this.a;
        }
    };
    x.c = x.b;
    assertEquals(10, x.c());
}
