public void testBreakAndThrow() {
    try {
        try {
            throw new Exception("throw me");
        } finally {
            break b;
        }
    } catch (Exception e) {
        fail();
    }
    System.out.println("ok then...");
}
