public void testIssue44() {
    try {
        parse(" var x=0,y=1;x||y=8;");
        fail("Should have thrown an exception");
    } catch (ParserException ex) {
        // expected
    }
}
