public void testIssue107() {
    try {
        RandomStringUtils.random(10, 0, 0, false, false, new char[]{}, new java.util.Random());
        fail("an exception should occur");
    } catch (ArrayIndexOutOfBoundsException ex) {
        // expected
    }
}
