public void testExceptionAfterException() {
    Object o = Mockito.mock(Object.class);
    Mockito.when(o.toString()).thenThrow(RuntimeException.class);
    try {
        o.toString();
        fail();
    } catch (RuntimeException e) {}
    Mockito.when(o.toString()).thenThrow(IllegalArgumentException.class);
    try {
        o.toString();
        fail();
    } catch (IllegalArgumentException e) {}
}
