public void test() throws Exception {
    A a = mock(A.class);
    when(a.getName()).thenReturn("1");
    assertEquals("1", a.getName());
}
